<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",859,894);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n    <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n    ",1075,1292);
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="<li id='left_current'><a href='~typelink~' class='thisclass'>~typename~</a></li>";
$z[6]=Array("field","",1717,1747);
$z[6][4]['name']="typename";
$z[6][4]['"']="";
$z[7]=Array("field","",2303,2324);
$z[7][4]['name']="content";
$z[8]=Array("include","",2530,2567);
$z[8][4]['filename']="footer.htm";

?>