<?php
$z[0]=Array("global","",49,75);
$z[0][4]['name']="cfg_powerby";
$z[1]=Array("global","",96,117);
$z[1][4]['name']="cfg_dz";
$z[2]=Array("global","",130,152);
$z[2][4]['name']="cfg_tel";
$z[3]=Array("type"," <a href=\"[field:typelink/]\">联系我们</a> ",235,316);
$z[3][4]['typeid']="21";
$z[4]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a> ",337,422);
$z[4][4]['typeid']="17";

?>